"""
SpillGuard Database Layer - PostgreSQL Persistence
Handles tables for spills, vessels, investigations, analyst notes, and analytics.
"""

import json
import os
from typing import List, Dict, Any, Optional

import psycopg
from psycopg.rows import dict_row

def get_connection():
    database_url = os.getenv(
        "DATABASE_URL",
        "postgresql://postgres:postgres@localhost:5432/spillguard",
    )
    return psycopg.connect(database_url, row_factory=dict_row)

def init_db():
    conn = get_connection()
    cursor = conn.cursor()

    # 1. Spills Table
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS spills (
            id TEXT PRIMARY KEY,
            title TEXT NOT NULL,
            severity TEXT NOT NULL,
            status TEXT NOT NULL,
            lat REAL NOT NULL,
            lon REAL NOT NULL,
            area_km2 REAL NOT NULL,
            volume_bbls INTEGER NOT NULL,
            confidence REAL NOT NULL,
            sensor TEXT NOT NULL,
            detected_at TEXT NOT NULL,
            wind TEXT NOT NULL,
            current TEXT NOT NULL,
            surface_temp TEXT NOT NULL,
            slick_type TEXT NOT NULL,
            thumbnail TEXT NOT NULL,
            primary_suspect_json TEXT NOT NULL,
            polygon_json TEXT NOT NULL
        )
    """)

    # 2. Vessels Table
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS vessels (
            imo INTEGER PRIMARY KEY,
            name TEXT NOT NULL,
            mmsi INTEGER NOT NULL,
            call_sign TEXT NOT NULL,
            flag TEXT NOT NULL,
            flag_code TEXT NOT NULL,
            type TEXT NOT NULL,
            length TEXT NOT NULL,
            beam TEXT NOT NULL,
            dwt TEXT NOT NULL,
            lat REAL NOT NULL,
            lon REAL NOT NULL,
            heading INTEGER NOT NULL,
            speed REAL NOT NULL,
            draft TEXT NOT NULL,
            last_ping TEXT NOT NULL,
            signal_health TEXT NOT NULL,
            is_dark INTEGER NOT NULL,
            dark_duration TEXT NOT NULL,
            risk_score INTEGER NOT NULL,
            risk_level TEXT NOT NULL,
            track_history_json TEXT NOT NULL
        )
    """)

    # 3. Investigations Table
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS investigations (
            incident_id TEXT PRIMARY KEY,
            case_code TEXT NOT NULL,
            classification TEXT NOT NULL,
            location_desc TEXT NOT NULL,
            lat_long TEXT NOT NULL,
            satellite_json TEXT NOT NULL,
            metocean_json TEXT NOT NULL,
            forensics_json TEXT NOT NULL,
            drift_sim_json TEXT NOT NULL,
            candidates_json TEXT NOT NULL
        )
    """)

    # 4. Analyst Notes Table (Persistent Operator Entries)
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS vessel_notes (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            imo INTEGER NOT NULL,
            note_text TEXT NOT NULL,
            author TEXT NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (imo) REFERENCES vessels(imo)
        )
    """)

    # 5. Analytics Table
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS analytics (
            id INTEGER PRIMARY KEY,
            kpis_json TEXT NOT NULL,
            monthly_trend_json TEXT NOT NULL,
            regional_dist_json TEXT NOT NULL,
            top_fleets_json TEXT NOT NULL
        )
    """)

    conn.commit()

    # Seed default data if empty
    cursor.execute("SELECT COUNT(*) AS spill_count FROM spills")
    if cursor.fetchone()["spill_count"] == 0:
        seed_initial_data(cursor)
        conn.commit()

    conn.close()

def seed_initial_data(cursor):
    # Seed Spills
    spills = [
        {
            "id": "SG-8842",
            "title": "Malacca Strait TSS Central Infiltration",
            "severity": "critical",
            "status": "UNATTRIBUTED DISCHARGE",
            "lat": 2.3812,
            "lon": 101.9124,
            "area_km2": 45.2,
            "volume_bbls": 18400,
            "confidence": 96.8,
            "sensor": "Sentinel-1A (C-Band IW VV+VH)",
            "detected_at": "2026-09-16 04:12:44 UTC",
            "wind": "14 kt NW (310°)",
            "current": "1.8 kt SE (135°)",
            "surface_temp": "29.4°C",
            "slick_type": "Heavy Crude Oil Emulsion",
            "thumbnail": "assets/images/sar_slick_detail.jpg",
            "primary_suspect": {
                "name": "MT Ocean Vanguard",
                "imo": 9482154,
                "confidence": 94.8,
                "matchType": "High Forensic Correlation"
            },
            "polygon": [
                [2.420, 101.860], [2.435, 101.905], [2.410, 101.960],
                [2.370, 101.980], [2.340, 101.930], [2.355, 101.875]
            ]
        },
        {
            "id": "SG-8839",
            "title": "Cape Rachado Outer Slick",
            "severity": "medium",
            "status": "UNDER INVESTIGATION",
            "lat": 2.5210,
            "lon": 101.7100,
            "area_km2": 12.8,
            "volume_bbls": 3600,
            "confidence": 88.4,
            "sensor": "ICEYE-X12 (X-Band StripMap)",
            "detected_at": "2026-09-16 01:45:10 UTC",
            "wind": "11 kt WNW (295°)",
            "current": "1.4 kt SE (140°)",
            "surface_temp": "29.6°C",
            "slick_type": "Bilge Wash / Fuel Oil Residue",
            "thumbnail": "assets/images/sar_slick_detail.jpg",
            "primary_suspect": {
                "name": "Nordic Titan",
                "imo": 9310842,
                "confidence": 41.2,
                "matchType": "Secondary Candidate"
            },
            "polygon": [
                [2.535, 101.690], [2.540, 101.730], [2.510, 101.745],
                [2.495, 101.715], [2.515, 101.685]
            ]
        },
        {
            "id": "SG-8831",
            "title": "Port Dickson South Discharge",
            "severity": "medium",
            "status": "FLAGGED PRELIMINARY",
            "lat": 2.2240,
            "lon": 102.0450,
            "area_km2": 5.4,
            "volume_bbls": 980,
            "confidence": 82.1,
            "sensor": "RADARSAT Constellation Mission-2",
            "detected_at": "2026-09-15 22:30:18 UTC",
            "wind": "9 kt N (350°)",
            "current": "1.6 kt SE (130°)",
            "surface_temp": "29.2°C",
            "slick_type": "Oily Water Separator Discharge",
            "thumbnail": "assets/images/sar_slick_detail.jpg",
            "primary_suspect": {
                "name": "Stellar Voyager",
                "imo": 9604122,
                "confidence": 18.5,
                "matchType": "Uncorrelated"
            },
            "polygon": [
                [2.235, 102.030], [2.240, 102.060], [2.215, 102.065], [2.210, 102.035]
            ]
        }
    ]

    for s in spills:
        cursor.execute("""
            INSERT INTO spills VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        """, (
            s["id"], s["title"], s["severity"], s["status"], s["lat"], s["lon"],
            s["area_km2"], s["volume_bbls"], s["confidence"], s["sensor"],
            s["detected_at"], s["wind"], s["current"], s["surface_temp"],
            s["slick_type"], s["thumbnail"],
            json.dumps(s["primary_suspect"]), json.dumps(s["polygon"])
        ))

    # Seed Vessels
    vessels = [
        {
            "imo": 9482154, "name": "MT Ocean Vanguard", "mmsi": 636019842, "call_sign": "ELVA8",
            "flag": "Liberia", "flag_code": "lr", "type": "VLCC Crude Tanker",
            "length": "333m", "beam": "60m", "dwt": "305,000",
            "lat": 2.285, "lon": 102.120, "heading": 132, "speed": 13.8, "draft": "19.2m",
            "last_ping": "3 min ago", "signal_health": "Dark", "is_dark": 1,
            "dark_duration": "3h 48m Blackout at Spill Origin", "risk_score": 95, "risk_level": "CRITICAL",
            "track_history": [
                [2.650, 101.450], [2.540, 101.680], [2.440, 101.880], [2.350, 102.010], [2.285, 102.120]
            ]
        },
        {
            "imo": 9310842, "name": "Nordic Titan", "mmsi": 538006214, "call_sign": "V7KT4",
            "flag": "Marshall Islands", "flag_code": "mh", "type": "Capesize Bulk Carrier",
            "length": "292m", "beam": "45m", "dwt": "180,000",
            "lat": 2.480, "lon": 101.820, "heading": 130, "speed": 11.4, "draft": "16.8m",
            "last_ping": "45 sec ago", "signal_health": "Good", "is_dark": 0,
            "dark_duration": "None (Continuous)", "risk_score": 42, "risk_level": "MEDIUM",
            "track_history": [
                [2.720, 101.350], [2.600, 101.600], [2.480, 101.820]
            ]
        },
        {
            "imo": 9604122, "name": "Stellar Voyager", "mmsi": 354891000, "call_sign": "3FGL9",
            "flag": "Panama", "flag_code": "pa", "type": "Ultra-Large Container (20k TEU)",
            "length": "399m", "beam": "59m", "dwt": "198,000",
            "lat": 2.180, "lon": 102.250, "heading": 128, "speed": 18.2, "draft": "14.5m",
            "last_ping": "1 min ago", "signal_health": "Good", "is_dark": 0,
            "dark_duration": "None (Continuous)", "risk_score": 18, "risk_level": "SAFE",
            "track_history": [
                [2.450, 101.800], [2.320, 102.020], [2.180, 102.250]
            ]
        },
        {
            "imo": 9284177, "name": "Seaborne Horizon", "mmsi": 636014522, "call_sign": "D5HG2",
            "flag": "Liberia", "flag_code": "lr", "type": "Chemical / Products Tanker",
            "length": "183m", "beam": "32m", "dwt": "50,000",
            "lat": 2.580, "lon": 101.620, "heading": 310, "speed": 12.0, "draft": "10.2m",
            "last_ping": "5 min ago", "signal_health": "Degraded", "is_dark": 1,
            "dark_duration": "1h 14m Intermittent Gap", "risk_score": 78, "risk_level": "HIGH",
            "track_history": [
                [2.420, 101.900], [2.500, 101.760], [2.580, 101.620]
            ]
        },
        {
            "imo": 9839923, "name": "CMA CGM Pegasus", "mmsi": 228389000, "call_sign": "FNKJ",
            "flag": "France", "flag_code": "fr", "type": "Container Ship",
            "length": "366m", "beam": "51m", "dwt": "155,000",
            "lat": 2.390, "lon": 102.040, "heading": 134, "speed": 16.5, "draft": "13.8m",
            "last_ping": "20 sec ago", "signal_health": "Good", "is_dark": 0,
            "dark_duration": "None", "risk_score": 12, "risk_level": "SAFE",
            "track_history": [
                [2.610, 101.650], [2.500, 101.840], [2.390, 102.040]
            ]
        },
        {
            "imo": 9145892, "name": "Apex Trader", "mmsi": 312548000, "call_sign": "V3TR8",
            "flag": "Belize", "flag_code": "bz", "type": "Aframax Crude Carrier",
            "length": "244m", "beam": "42m", "dwt": "105,000",
            "lat": 2.620, "lon": 101.550, "heading": 135, "speed": 9.8, "draft": "15.1m",
            "last_ping": "2h ago", "signal_health": "Dark", "is_dark": 1,
            "dark_duration": "5h 22m Blackout", "risk_score": 88, "risk_level": "CRITICAL",
            "track_history": [
                [2.780, 101.240], [2.620, 101.550]
            ]
        },
        {
            "imo": 9741203, "name": "Pacific Sentinel", "mmsi": 563044100, "call_sign": "9V648",
            "flag": "Singapore", "flag_code": "sg", "type": "LPG Tanker",
            "length": "226m", "beam": "37m", "dwt": "55,000",
            "lat": 2.310, "lon": 101.990, "heading": 312, "speed": 14.1, "draft": "11.4m",
            "last_ping": "1 min ago", "signal_health": "Good", "is_dark": 0,
            "dark_duration": "None", "risk_score": 14, "risk_level": "SAFE",
            "track_history": [
                [2.150, 102.260], [2.310, 101.990]
            ]
        }
    ]

    for v in vessels:
        cursor.execute("""
            INSERT INTO vessels VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        """, (
            v["imo"], v["name"], v["mmsi"], v["call_sign"], v["flag"], v["flag_code"],
            v["type"], v["length"], v["beam"], v["dwt"], v["lat"], v["lon"],
            v["heading"], v["speed"], v["draft"], v["last_ping"], v["signal_health"],
            v["is_dark"], v["dark_duration"], v["risk_score"], v["risk_level"],
            json.dumps(v["track_history"])
        ))

    # Seed Initial Analyst Note for MT Ocean Vanguard
    cursor.execute("""
        INSERT INTO vessel_notes (imo, note_text, author) VALUES (%s, %s, %s)
    """, (9482154, "Automated Alert: Transponder silent for 3h 48m in TSS Sector 4. High correlation with Sentinel-1A SAR slick #SG-8842.", "SYSTEM_AUTO_FORENSIC"))

    # Seed Investigation Case SG-8842
    satellite_info = {
        "name": "Sentinel-1A SAR",
        "passTime": "2026-09-16 04:12:44 UTC",
        "orbit": "Ascending Path 148, Frame 582",
        "mode": "Interferometric Wide (IW)",
        "polarization": "VV + VH Dual-Pol",
        "spatialResolution": "10m x 10m"
    }

    metocean_info = {
        "windSpeed": "14.2 knots",
        "windDir": "310° (NW)",
        "surfaceCurrent": "1.8 knots @ 135° (SE)",
        "driftVelocity": "2.1 knots @ 138°",
        "sst": "29.4 °C",
        "waveHeight": "0.8m significant",
        "coralReefProximity": "8.4 nautical miles (Pulau Besar MPA)"
    }

    forensics_info = {
        "polarimetricRatio": "VV/VH ratio drops by -7.4 dB within anomaly zone (characteristic of crude oil dampening capillary-gravity waves)",
        "meanThickness": "1.42 mm (emulsified core exceeds 3.8 mm)",
        "slickTotalArea": "45.2 km²",
        "slickVolumeEst": "18,400 bbls (2,925 m³)",
        "sha256DossierHash": "e4b983c27189fa3198de7e5a01bc6f4439c09d57a2c4187f1b70298e10fa31ce"
    }

    drift_sim = {
        "timeSteps": [
            {"time": "T-0h (Now / SAR Scan)", "label": "SAR Acquisition", "coords": [2.381, 101.912]},
            {"time": "T-3h (01:12 UTC)", "label": "Lagrangian Step -3h", "coords": [2.410, 101.885]},
            {"time": "T-6h (22:12 UTC)", "label": "Lagrangian Step -6h", "coords": [2.438, 101.860]},
            {"time": "T-9h (19:12 UTC)", "label": "Slick Origin Confluence", "coords": [2.465, 101.835]}
        ],
        "originEstimate": {
            "coords": [2.445, 101.855],
            "timestamp": "2026-09-15 23:45 UTC ± 35 min",
            "accuracyRadius": "0.4 nautical miles"
        }
    }

    candidates = [
        {
            "rank": 1,
            "name": "MT Ocean Vanguard",
            "imo": 9482154,
            "flag": "Liberia 🇱🇷",
            "type": "VLCC Crude Tanker",
            "confidence": 94.8,
            "matchLevel": "PRIMARY SUSPECT",
            "evidence": [
                {"type": "red", "text": "AIS transponder disabled for 3h 48m precisely across slick origin zone"},
                {"type": "red", "text": "Vessel draft dropped by 1.6m mid-transit (-2,400 tonnes displacement)"},
                {"type": "red", "text": "Speed anomaly: decelerated from 14.4 kt to 6.4 kt during transponder blackout"},
                {"type": "amber", "text": "Lagrangian reverse-drift origin trajectory aligns with ship course (r = 0.984)"},
                {"type": "amber", "text": "SAR backscatter detects distinctive dark trailing stern wake plume on swath"}
            ]
        },
        {
            "rank": 2,
            "name": "Nordic Titan",
            "imo": 9310842,
            "flag": "Marshall Islands 🇲🇭",
            "type": "Bulk Carrier",
            "confidence": 41.2,
            "matchLevel": "LOW PROBABILITY",
            "evidence": [
                {"type": "neutral", "text": "Passed 4.8 nm downwind of estimated origin coordinates"},
                {"type": "neutral", "text": "Maintained continuous uninterrupted AIS broadcast"},
                {"type": "neutral", "text": "Engine RPM and draft telemetry show nominal steady cruising"}
            ]
        },
        {
            "rank": 3,
            "name": "Stellar Voyager",
            "imo": 9604122,
            "flag": "Panama 🇵🇦",
            "type": "Container Carrier",
            "confidence": 18.5,
            "matchLevel": "EXCLUDED",
            "evidence": [
                {"type": "neutral", "text": "Transited TSS corridor 8.5 hours after calculated discharge timestamp"},
                {"type": "neutral", "text": "Speed maintained steady at 18.2 kt throughout sector"}
            ]
        }
    ]

    cursor.execute("""
        INSERT INTO investigations VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
    """, (
        "SG-8842",
        "CASE-2026-SG8842-MLC",
        "MARPOL Annex I Hydrocarbon Discharge",
        "Strait of Malacca TSS Sector 4 (Offshore Melaka)",
        "02°22'52\"N, 101°54'45\"E",
        json.dumps(satellite_info),
        json.dumps(metocean_info),
        json.dumps(forensics_info),
        json.dumps(drift_sim),
        json.dumps(candidates)
    ))

    # Seed Analytics
    kpis = {
        "totalDetections90d": 1248,
        "volumeDischargedBbls": "342,800 bbls",
        "attributionSuccessRate": "92.4%",
        "penaltiesLeviedUSD": "$48.2M"
    }

    monthly_trend = [
        {"month": "Apr", "catastrophic": 2, "significant": 8, "minor": 24},
        {"month": "May", "catastrophic": 3, "significant": 11, "minor": 28},
        {"month": "Jun", "catastrophic": 1, "significant": 7, "minor": 19},
        {"month": "Jul", "catastrophic": 4, "significant": 14, "minor": 32},
        {"month": "Aug", "catastrophic": 2, "significant": 9, "minor": 22},
        {"month": "Sep (MTD)", "catastrophic": 5, "significant": 16, "minor": 38}
    ]

    regional_dist = [
        {"region": "Strait of Malacca", "percent": 42, "color": "#FF4438"},
        {"region": "Persian Gulf", "percent": 28, "color": "#FFB020"},
        {"region": "South China Sea", "percent": 14, "color": "#00D4FF"},
        {"region": "North Sea", "percent": 10, "color": "#2BD97C"},
        {"region": "Gulf of Mexico", "percent": 6, "color": "#90A4BE"}
    ]

    top_fleets = [
        {"name": "Liberia (FOC)", "count": 48, "pct": 85, "color": "red-fill"},
        {"name": "Panama (FOC)", "count": 39, "pct": 70, "color": "red-fill"},
        {"name": "Gabon (Dark Tanker Fleet)", "count": 31, "pct": 56, "color": "amber-fill"},
        {"name": "Marshall Islands", "count": 18, "pct": 32, "color": "cyan-fill"},
        {"name": "Cook Islands", "count": 14, "pct": 25, "color": "cyan-fill"}
    ]

    cursor.execute("""
        INSERT INTO analytics VALUES (1, %s, %s, %s, %s)
    """, (
        json.dumps(kpis),
        json.dumps(monthly_trend),
        json.dumps(regional_dist),
        json.dumps(top_fleets)
    ))

# Helper Query Functions
def query_spills(severity: Optional[str] = None) -> List[Dict[str, Any]]:
    conn = get_connection()
    cursor = conn.cursor()
    if severity:
        cursor.execute("SELECT * FROM spills WHERE severity = %s", (severity,))
    else:
        cursor.execute("SELECT * FROM spills")
    rows = cursor.fetchall()
    conn.close()

    result = []
    for r in rows:
        result.append({
            "id": r["id"],
            "title": r["title"],
            "severity": r["severity"],
            "status": r["status"],
            "coords": [r["lat"], r["lon"]],
            "areaKm2": r["area_km2"],
            "volumeBbls": r["volume_bbls"],
            "confidence": r["confidence"],
            "sensor": r["sensor"],
            "detectedAt": r["detected_at"],
            "wind": r["wind"],
            "current": r["current"],
            "surfaceTemp": r["surface_temp"],
            "slickType": r["slick_type"],
            "thumbnail": r["thumbnail"],
            "primarySuspect": json.loads(r["primary_suspect_json"]),
            "slickPolygon": json.loads(r["polygon_json"])
        })
    return result

def query_spill_by_id(spill_id: str) -> Optional[Dict[str, Any]]:
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM spills WHERE id = %s", (spill_id,))
    r = cursor.fetchone()
    conn.close()
    if not r:
        return None
    return {
        "id": r["id"],
        "title": r["title"],
        "severity": r["severity"],
        "status": r["status"],
        "coords": [r["lat"], r["lon"]],
        "areaKm2": r["area_km2"],
        "volumeBbls": r["volume_bbls"],
        "confidence": r["confidence"],
        "sensor": r["sensor"],
        "detectedAt": r["detected_at"],
        "wind": r["wind"],
        "current": r["current"],
        "surfaceTemp": r["surface_temp"],
        "slickType": r["slick_type"],
        "thumbnail": r["thumbnail"],
        "primarySuspect": json.loads(r["primary_suspect_json"]),
        "slickPolygon": json.loads(r["polygon_json"])
    }

def query_vessels(filter_type: Optional[str] = None, search: Optional[str] = None) -> List[Dict[str, Any]]:
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM vessels")
    rows = cursor.fetchall()
    conn.close()

    result = []
    for r in rows:
        v = {
            "imo": r["imo"],
            "name": r["name"],
            "mmsi": r["mmsi"],
            "callSign": r["call_sign"],
            "flag": r["flag"],
            "flagCode": r["flag_code"],
            "type": r["type"],
            "length": r["length"],
            "beam": r["beam"],
            "dwt": r["dwt"],
            "coords": [r["lat"], r["lon"]],
            "heading": r["heading"],
            "speed": r["speed"],
            "draft": r["draft"],
            "lastAisPing": r["last_ping"],
            "signalHealth": r["signal_health"],
            "isDarkVessel": bool(r["is_dark"]),
            "darkDuration": r["dark_duration"],
            "riskScore": r["risk_score"],
            "riskLevel": r["risk_level"],
            "trackHistory": json.loads(r["track_history_json"])
        }

        # Search filter
        if search:
            s = search.lower()
            if not (s in v["name"].lower() or str(v["imo"]) in s or s in v["flag"].lower() or s in v["type"].lower()):
                continue

        # Type filter
        if filter_type == "dark" and not v["isDarkVessel"]:
            continue
        if filter_type == "tankers" and "tanker" not in v["type"].lower() and "carrier" not in v["type"].lower():
            continue
        if filter_type == "high-risk" and v["riskScore"] < 75:
            continue

        result.append(v)
    return result

def add_vessel_note(imo: int, note_text: str, author: str = "Operator"):
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("""
        INSERT INTO vessel_notes (imo, note_text, author)
        VALUES (%s, %s, %s)
        RETURNING id
    """, (imo, note_text, author))
    conn.commit()
    note_id = cursor.fetchone()["id"]
    conn.close()
    return {"id": note_id, "imo": imo, "note": note_text, "author": author}

def get_vessel_notes(imo: int) -> List[Dict[str, Any]]:
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM vessel_notes WHERE imo = %s ORDER BY created_at DESC", (imo,))
    rows = cursor.fetchall()
    conn.close()
    return [{"id": r["id"], "imo": r["imo"], "note": r["note_text"], "author": r["author"], "createdAt": r["created_at"]} for r in rows]

def query_investigation(incident_id: str) -> Optional[Dict[str, Any]]:
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM investigations WHERE incident_id = %s", (incident_id,))
    r = cursor.fetchone()
    conn.close()
    if not r:
        return None
    return {
        "incidentId": r["incident_id"],
        "caseCode": r["case_code"],
        "classification": r["classification"],
        "locationDesc": r["location_desc"],
        "latLong": r["lat_long"],
        "satellite": json.loads(r["satellite_json"]),
        "metocean": json.loads(r["metocean_json"]),
        "forensics": json.loads(r["forensics_json"]),
        "driftSimulation": json.loads(r["drift_sim_json"]),
        "candidates": json.loads(r["candidates_json"])
    }

def query_analytics() -> Dict[str, Any]:
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM analytics WHERE id = 1")
    r = cursor.fetchone()
    conn.close()
    if not r:
        return {}
    return {
        "kpis": json.loads(r["kpis_json"]),
        "monthlyTrend": json.loads(r["monthly_trend_json"]),
        "regionalDistribution": json.loads(r["regional_dist_json"]),
        "topFlaggedFleets": json.loads(r["top_fleets_json"])
    }
